### ISSUE TITLE
The improvement for Linkis Website To Do List

### ISSUE THREAD

**Issue by Beacontownfc** [apache/linkis-website#353]
The following are outstanding / completed issues:

- [x] [Linkis website checks](https://github.com/apache/incubator-linkis-website/issues/269), This PR #283 solved this issue;
- [x]  [The website Github icon need to be changed](https://github.com/apache/incubator-linkis-website/issues/345), This PR #342 solved this issue;
- [x]  [The Linkis website needs to add a github action to check whether the linkis website link is available](https://github.com/apache/incubator-linkis-website/issues/354), This PR #341 solved this issue;
- [x]  [[Bug]docs version page display not centered](https://github.com/apache/incubator-linkis-website/issues/193), This PR #301 solved this issue;
- [x] [[Improvement] The team page needs to add a committer presentation](https://github.com/apache/incubator-linkis-website/issues/347), This PR #346 solved this issue;
- [x] [Branch merge issue](https://github.com/apache/incubator-linkis-website/issues/356), This PR #343 solved this issue;
- [x] [Some links in the linkis website need to fix](https://github.com/apache/incubator-linkis-website/issues/357), This PR #348 solved this issue;
- [x] [Some parts of the front-end compilation doc are redundant](https://github.com/apache/incubator-linkis-website/issues/364), This PR #365 fixed the issue.
- [x] [[Improvement] Unification of usage specifications for representing Linkis installation directories](https://github.com/apache/incubator-linkis-website/issues/326), this PR #363 fixed the issue.
- [x] [[Improvement][Verify the candidate Version] add the compilation verification of the web](https://github.com/apache/incubator-linkis-website/issues/264), this PR #358 fixed the issue.
- [x] [[Improvement] The top bar doc version display style need to optimize](https://github.com/apache/incubator-linkis-website/issues/359), this PR #362 fixed the issue.
- [x] [[Improvement] Add a Blessing Wall page to the website](https://github.com/apache/incubator-linkis-website/issues/375), this PR #373 fixed the issue.
- [x] [[Improvement] The website need to add an auto comment bot](https://github.com/apache/incubator-linkis-website/issues/379), This PR #378 fixed this issue.
- [x] [[Improvement] The website requires an auto closing issue bot](https://github.com/apache/incubator-linkis-website/issues/391), This PR #392 fixed this issue.
- [x] [The team page of the website is not adapted to the mobile terminal](https://github.com/apache/incubator-linkis-website/issues/401), This PR #400 fixed this issue.
- [x] [Some github action codes in the website repository are redundant](https://github.com/apache/incubator-linkis-website/issues/397), This PR #398 fixed the issue.
- [x] [Can the same docs version support multiple routing path](https://github.com/facebook/docusaurus/discussions/7502#discussioncomment-2827567), this PR #428 fixed the issue.
